const KEY='verse_wiki_v1',$=s=>document.querySelector(s),uid=()=>Math.random().toString(36).slice(2,9);
const E=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const N=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
const DEF={ac:'#e58fb0',bg:'#fdf6f8',ink:'#3b2a33'};
const ABOUT_DEF={title:'About Me',subtitle:'Một góc nhỏ để bạn giới thiệu về mình',text:'Viết đôi điều về bạn, sở thích, dự án hoặc câu chuyện riêng ở đây.',bg:'#fff7fa',ac:'#e58fb0',ink:'#3b2a33',img:'',radius:28,blocks:[]};
const CFG=window.WIKI_CONFIG||{},SB_URL=CFG.url||'',SB_KEY=CFG.key||'',BUCKET='wiki-media';
const sb=(window.supabase&&SB_URL&&SB_KEY&&!/DAN_/.test(SB_URL))?supabase.createClient(SB_URL,SB_KEY):null;
function toast(t){let d=document.getElementById('sbtoast');if(!d){d=document.createElement('div');d.id='sbtoast';d.style.cssText='position:fixed;right:14px;bottom:14px;z-index:9999;background:#3b2a33;color:#fff;padding:8px 14px;border-radius:12px;font:500 13px system-ui;opacity:.92;transition:opacity .4s';document.body.appendChild(d)}d.textContent=t;d.style.opacity='.92';clearTimeout(d._t);d._t=setTimeout(()=>d.style.opacity='0',2200)}
async function pushRemote(s){if(!sb)throw new Error('Chưa cấu hình Supabase trong config.js');if(!admin)throw new Error('Bạn chưa đăng nhập admin');const payload=typeof s==='string'?JSON.parse(s):s;const{error}=await sb.from('wiki').upsert({id:'main',data:payload,updated_at:new Date().toISOString()},{onConflict:'id'});if(error)throw error;return true}
let D;
const idb=()=>new Promise((ok,no)=>{const q=indexedDB.open('verse_wiki_db',1);q.onupgradeneeded=()=>q.result.createObjectStore('kv');q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)});
const idbGet=()=>idb().then(db=>new Promise((ok,no)=>{const q=db.transaction('kv').objectStore('kv').get(KEY);q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)}));
function boot(raw){try{D=JSON.parse(raw)}catch(e){}
if(!D)D={s:{name:'Verse Wiki',note:'Thư viện các thế giới của tôi',...DEF,cover:''},about:{...ABOUT_DEF},v:[{id:'v1',n:'Verse mẫu',d:'Một thế giới để bạn bắt đầu.',c:'#9b8bd6',img:'',s:[{id:'s1',n:'Nhân vật',e:[{id:'e1',n:'Nhân vật mẫu',img:'',imgSize:100,b:[{t:'info',v:'Tuổi: 17\nVai trò: Nhân vật chính'},{t:'heading',v:'Giới thiệu'},{t:'text',v:'Viết tiểu sử, ngoại hình, tính cách... ở đây. Mỗi nhân vật tự đặt tiêu đề mục riêng.'}]}]},{id:'s2',n:'Địa điểm',e:[]},{id:'s3',n:'Cốt truyện',e:[]},{id:'s4',n:'Timeline',e:[]}]}]};
if(D.s)delete D.s.pw;D.about={...ABOUT_DEF,...(D.about||{})};D.about.blocks=D.about.blocks||[];D.v=D.v||[];D.v.forEach(v=>{v.s=v.s||[];v.s.forEach(s=>{s.e=s.e||[];s.e.forEach(e=>{e.imgSize=e.imgSize||100;e.b=e.b||[];e.b.forEach(b=>{if(b.t==='img'||b.t==='imgtext')b.size=b.size||100})})})});}
let admin=false;
const memUse=()=>JSON.stringify(D).length/1e6;
async function cacheLocal(s){try{const db=await idb();await new Promise((ok,no)=>{const tx=db.transaction('kv','readwrite');tx.objectStore('kv').put(s,KEY);tx.oncomplete=ok;tx.onerror=()=>no(tx.error);tx.onabort=()=>no(tx.error)})}catch(e){}try{if(s.length<4e6)localStorage.setItem(KEY,s);else localStorage.removeItem(KEY)}catch(e){}}
async function save(){const s=JSON.stringify(D);if(!sb){await cacheLocal(s);alert('Chưa kết nối Supabase. Thay đổi này chỉ được lưu tạm trên máy này. Hãy kiểm tra config.js.');return false}if(!admin){alert('Bạn cần đăng nhập admin trước khi lưu thay đổi.');return false}try{await pushRemote(s);await cacheLocal(s);toast('✓ Đã lưu lên web');return true}catch(e){alert('Không lưu được lên Supabase: '+(e?.message||e)+'\n\nThay đổi chưa được xác nhận là đã đăng lên web. Hãy kiểm tra setup.sql / RLS và kết nối mạng.');return false}}
function theme(){const r=document.documentElement.style,s=D.s;r.setProperty('--ac',s.ac);r.setProperty('--bg',s.bg);r.setProperty('--ink',s.ink)}
const V=id=>D.v.find(x=>x.id==id),S=(v,s)=>V(v)?.s.find(x=>x.id==s),T=(v,s,e)=>S(v,s)?.e.find(x=>x.id==e);
const bg=u=>u?`style="background-image:url('${u}')"`:'';
const linkFix=u=>{u=String(u??'').trim();const m=/\b(?:drive|docs)\.google\.com\/(?:file\/d\/|open\?id=|document\/d\/|spreadsheets\/d\/|presentation\/d\/|uc\?(?:export=\w+&)?id=)([\w-]{10,})/.exec(u);if(m)return'https://drive.google.com/thumbnail?id='+m[1]+'&sz=w1600';return/dropbox\.com\//.test(u)?u.replace(/([?&])dl=0/,'$1raw=1'):u};
function items(){const a=[];D.v.forEach(v=>{a.push({k:'Verse',n:v.n,sub:v.d,h:`#/v/${v.id}`,img:v.img,hay:v.n+' '+v.d});v.s.forEach(s=>{a.push({k:'Mục',n:s.n,sub:v.n,h:`#/s/${v.id}/${s.id}`,hay:s.n+' '+v.n});s.e.forEach(e=>a.push({k:'Bài viết',n:e.n,sub:v.n+' › '+s.n,h:`#/e/${v.id}/${s.id}/${e.id}`,img:e.img,hay:e.n+' '+v.n+' '+s.n+' '+e.b.map(b=>b.t=='audio'||b.t=='video'?'':b.v||'').join(' ')}))})});return a}
async function upMedia(dataUrl){const m=/^data:([^;,]+)/.exec(dataUrl),type=m?m[1]:'application/octet-stream',ext=({'image/jpeg':'jpg','image/png':'png','image/gif':'gif','image/webp':'webp','image/svg+xml':'svg','image/avif':'avif','audio/mpeg':'mp3','audio/mp4':'m4a','audio/wav':'wav','audio/ogg':'ogg','video/mp4':'mp4','video/webm':'webm'})[type]||(type.split('/')[1]||'bin').replace(/\W/g,''),blob=await(await fetch(dataUrl)).blob(),path=Date.now()+'-'+uid()+'.'+ext,{error}=await sb.storage.from(BUCKET).upload(path,blob,{contentType:type,cacheControl:'31536000'});if(error)throw error;return sb.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}
function readImg(f,cb,isImg){readImg0(f,async u=>{if(!u||!sb||!admin||!/^data:/.test(u))return cb(u);try{toast('Đang tải lên…');const url=await upMedia(u);toast('✓ Đã tải lên');cb(url)}catch(e){alert('Không tải lên Supabase Storage được ('+(e.message||e)+'). File tạm thời được nhúng vào dữ liệu; hãy kiểm tra đã chạy phần bucket trong setup.sql chưa.');cb(u)}},isImg)}
function readImg0(f,cb,isImg){const ext=(f.name.split('.').pop()||'').toLowerCase(),IM={jpg:'image/jpeg',jpeg:'image/jpeg',jfif:'image/jpeg',pjpeg:'image/jpeg',png:'image/png',gif:'image/gif',webp:'image/webp',avif:'image/avif',bmp:'image/bmp',svg:'image/svg+xml',ico:'image/x-icon',heic:'image/heic',heif:'image/heif'},MD={mp3:'audio/mpeg',m4a:'audio/mp4',wav:'audio/wav',ogg:'audio/ogg',oga:'audio/ogg',aac:'audio/aac',flac:'audio/flac',mp4:'video/mp4',webm:'video/webm',mov:'video/quicktime',m4v:'video/mp4'};let type=f.type||'';const img=isImg||type.startsWith('image/');if(img&&!type.startsWith('image/'))type=IM[ext]||'';if(!img&&!type)type=MD[ext]||'';const retype=u=>type?String(u).replace(/^data:[^;,]*/,'data:'+type):u;const r=new FileReader();r.onerror=()=>{alert('Không đọc được file này, hãy thử file khác.');cb(null)};r.onload=()=>{const raw=retype(r.result);if(!img||type==='image/gif'||type==='image/svg+xml')return cb(raw);const fail=()=>{alert('File ảnh này trình duyệt không xem được (có thể là HEIC/RAW hoặc file lỗi). Hãy lưu ảnh thành JPG/PNG rồi thêm lại nhé.');cb(null)};const i=new Image();i.onload=()=>{try{const w=i.naturalWidth||i.width,h=i.naturalHeight||i.height;if(!w||!h)return fail();const m=Math.min(1,1600/Math.max(w,h)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(w*m));c.height=Math.max(1,Math.round(h*m));const x=c.getContext('2d');x.drawImage(i,0,0,c.width,c.height);let alpha=false;if(/png|webp|avif|bmp|icon/.test(type)){const d=x.getImageData(0,0,c.width,c.height).data;for(let k=3;k<d.length;k+=4)if(d[k]<250){alpha=true;break}}let out;if(alpha){out=c.toDataURL('image/png');if(out.length>4e6){const wp=c.toDataURL('image/webp',.9);if(wp.startsWith('data:image/webp'))out=wp}}else out=c.toDataURL('image/jpeg',.88);cb(out.startsWith('data:image/')&&out.length>100?out:raw)}catch(e){type.startsWith('image/')&&!/heic|heif/.test(type)?cb(raw):fail()}};i.onerror=fail;i.src=raw};r.readAsDataURL(f)}
function embed(u){const m=/(?:youtu\.be\/|v=|embed\/)([\w-]{11})/.exec(u||'');return m?`<iframe src="https://www.youtube.com/embed/${m[1]}" allowfullscreen></iframe>`:`<video controls src="${E(u)}"></video>`}
const AR=v=>/^\d{1,2}\/\d{1,2}$/.test(v||'')?v:'';
function imgStyle(size=100,ar=''){ar=AR(ar);return `style="width:${Math.max(10,Math.min(100,+size||100))}%;max-width:100%;height:auto${ar?`;aspect-ratio:${ar};object-fit:cover`:''}"`}
const AR_OPTS=[['','Tự do'],['1/1','1:1 (vuông)'],['4/3','4:3'],['3/4','3:4'],['16/9','16:9'],['9/16','9:16'],['3/2','3:2'],['2/3','2:3']];
const arSelect=(o,f,v,l='Tỉ lệ ảnh')=>`<label class="size-control">${l} <select class="f" data-o="${o}" data-f="${f}">${AR_OPTS.map(([k,n])=>`<option value="${k}" ${(v||'')===k?'selected':''}>${n}</option>`).join('')}</select></label>`;
const del=(a,x,l='Xóa')=>`<button class="btn d" data-a="${a}" data-danger ${x}>${l}</button>`;
const hasFr=o=>o.bc||o.bi||(o.far&&AR(o.far))||(o.fw&&+o.fw<100)||(o.br!==undefined&&o.br!=='')||(o.bt!==undefined&&o.bt!=='');
const dcs=(o,force)=>{const n=(k,d)=>o[k]===undefined||o[k]===''||isNaN(+o[k])?d:+o[k];let s='';if(force||hasFr(o)){const a=n('bo',55)/100,g=o.bi?`linear-gradient(rgba(255,255,255,${a}),rgba(255,255,255,${a})),url('${o.bi}') center/cover no-repeat`:(o.bc||'#ffffff');s+=`--dbg:${g};--dbr:${Math.max(0,Math.min(80,n('br',18)))}px;--dbq:${(1-Math.max(0,Math.min(100,n('bt',0)))/100).toFixed(2)};`}if(o.tc)s+=`color:${o.tc};`;return s};
const dcw=(o,h)=>{if(!(hasFr(o)||o.tc))return h;if(!h){if(!(o.t==='img'||o.t==='imgtext'||o.t==='text'))return h;h='<div style="min-height:180px"></div>'}let x=dcs(o);if(AR(o.far))x+=`aspect-ratio:${AR(o.far)};display:flex;flex-direction:column;justify-content:center;`;if(o.fw&&+o.fw<100)x+=`width:${Math.max(10,+o.fw)}%;`;return`<div class="dcw" style="${x}">${h}</div>`};
const FX=(o,k)=>{const n=(p,d)=>o[k+p]===undefined||o[k+p]===''?d:+o[k+p];return{h:n('H',290),z:n('Z',100),x:n('X',50),y:n('Y',50)}};
const fxCss=(o,k)=>{const f=FX(o,k);return`background-position:${f.x}% ${f.y}%;transform:scale(${f.z/100});transform-origin:${f.x}% ${f.y}%`};
const fx=(o,k)=>o[k]?`<i class="fx" style="background-image:url('${o[k]}');${fxCss(o,k)}"></i>`:'';
const fxEditor=(o,k,ob)=>{if(!ob[k])return'<p class="muted">Thêm ảnh để chỉnh kích thước.</p>';const f=FX(ob,k),r=(l,s,mn,mx,v,p)=>`<label class="size-control"><span>${l}</span><input type="range" min="${mn}" max="${mx}" step="${s}" value="${v}" data-o="${o}" data-f="${k}${p}" data-pv="${o}:${k}"><b>${v}${p=='H'?'px':'%'}</b></label>`;return`<div class="fxbox" data-pv="${o}:${k}" style="height:${Math.min(f.h,260)}px"><i class="fx" style="background-image:url('${ob[k]}');${fxCss(ob,k)}"></i></div><div class="fx-controls">${r('Chiều cao',10,180,520,f.h,'H')}${r('Phóng to',5,100,250,f.z,'Z')}${r('Vị trí ngang',1,0,100,f.x,'X')}${r('Vị trí dọc',1,0,100,f.y,'Y')}<button class="btn g" data-a="resfx" data-o="${o}" data-k="${k}">Đặt lại</button></div>`};
function fxLive(t,ob){const k=t.dataset.pv.split(':').pop(),bx=[...document.querySelectorAll('.fxbox')].find(x=>x.dataset.pv==t.dataset.pv),i=bx&&bx.querySelector('.fx');if(!i)return;const f=FX(ob,k);bx.style.height=Math.min(f.h,260)+'px';i.style.backgroundPosition=f.x+'% '+f.y+'%';i.style.transform='scale('+f.z/100+')';i.style.transformOrigin=f.x+'% '+f.y+'%';const b=t.parentElement.querySelector('b');if(b)b.textContent=t.value+(t.dataset.f.endsWith('H')?'px':'%')}
function blockView(b){const v=E(b.v);switch(b.t){case'heading':return`<h3>${v}</h3>`;case'text':return`<p style="white-space:pre-wrap">${v}</p>`;case'img':return b.img?`<figure><img ${imgStyle(b.size,b.ar)} src="${b.img}" alt="${E(b.cap)}"><figcaption>${E(b.cap)}</figcaption></figure>`:'';case'imgtext':return`<div class="split ${b.side=='R'?'R':''}">${b.img?`<img ${imgStyle(b.size,b.ar)} src="${b.img}" alt="">`:''}<p>${v}</p></div>`;case'video':return b.v?embed(b.v):'';case'audio':return'';case'info':return`<table>${(b.v||'').split('\n').filter(x=>x.trim()).map(l=>{const i=l.indexOf(':');return i<0?`<tr><td colspan=2>${E(l)}</td></tr>`:`<tr><td>${E(l.slice(0,i))}</td><td>${E(l.slice(i+1))}</td></tr>`}).join('')}</table>`}return''}
function aboutBlockView(b){if(b.t==='heading')return`<h3>${E(b.v)}</h3>`;if(b.t==='text')return`<p class="about-text">${E(b.v)}</p>`;if(b.t==='img')return b.img?`<div class="about-image"><img ${imgStyle(b.size,b.ar)} src="${b.img}" alt=""></div>`:'';if(b.t==='imgtext')return`<div class="about-split ${b.side==='R'?'R':''}">${b.img?`<img ${imgStyle(b.size,b.ar)} src="${b.img}" alt="">`:''}<p>${E(b.v)}</p></div>`;return''}
const GRIP='<span class="grip" data-grip title="Nhấn giữ rồi kéo lên/xuống để đổi thứ tự">⋮⋮</span>';
function ytId(u){const m=/(?:youtu\.be\/|v=|embed\/|shorts\/)([\w-]{11})/.exec(u||'');return m?m[1]:''}
function playlist(e){const t=e.b.filter(b=>b.t==='audio'&&b.v);if(!t.length)return'';return`<section class="playlist" data-pl><div class="pl-head"><span class="pl-ic">♪</span><div><b>Playlist</b><small>${t.length} bài</small></div></div><p class="pl-hint">Trình duyệt đang chặn tự phát — chạm vào trang hoặc bấm ▶ để nghe.</p><ol class="pl-list">${t.map((b,i)=>`<li class="pl-item" data-src="${E(b.v)}" data-auto="${b.auto?1:0}"><span class="no">${i+1}</span><span class="nm">${E(b.title||'Bài '+(i+1))}</span>${b.auto?'<small>tự động phát</small>':''}</li>`).join('')}</ol><div class="pl-bar"><button class="pl-b" data-pl-prev title="Bài trước">⏮</button><button class="pl-b pl-pp" data-pl-pp title="Phát / Tạm dừng">▶</button><button class="pl-b" data-pl-next title="Bài sau">⏭</button><span class="pl-t" data-cur>0:00</span><input class="pl-seek" type="range" min="0" max="1000" value="0"><span class="pl-t" data-dur>0:00</span></div><div class="pl-yt"><div id="plyt"></div></div></section>`}
let PLK=null;
function loadYT(cb){if(window.YT&&YT.Player)return cb();const q=window._ytq=window._ytq||[];q.push(cb);if(!window._ytl){window._ytl=1;const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';document.head.appendChild(s);const prev=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{prev&&prev();q.splice(0).forEach(f=>f())}}}
function initPlaylist(){if(PLK){PLK();PLK=null}const pl=$('[data-pl]');if(!pl)return;
const its=[...pl.querySelectorAll('.pl-item')],pp=pl.querySelector('[data-pl-pp]'),seek=pl.querySelector('.pl-seek'),tc=pl.querySelector('[data-cur]'),td=pl.querySelector('[data-dur]');
const au=new Audio();au.preload='metadata';let yt=null,ready=false,ytq=[],mode='a',cur=-1,playing=false,seeking=false,dead=false;
const fmt=s=>{s=Math.max(0,s|0);return(s/60|0)+':'+String(s%60).padStart(2,'0')};
const mark=i=>{cur=i;its.forEach((x,k)=>x.classList.toggle('on',k==i))};
const ui=p=>{playing=p;pp.textContent=p?'❚❚':'▶';pl.classList.toggle('playing',p);if(p)pl.classList.remove('blocked')};
const prog=()=>{let c=0,d=0;if(mode=='y'){if(yt&&ready&&yt.getCurrentTime){c=yt.getCurrentTime();d=yt.getDuration()}}else{c=au.currentTime;d=au.duration}if(!isFinite(d))d=0;tc.textContent=fmt(c);td.textContent=fmt(d);if(!seeking)seek.value=d?Math.round(c/d*1000):0};
const timer=setInterval(prog,400);
const ensureYT=(id,go)=>loadYT(()=>{if(dead)return;if(ready){go();return}ytq.push(go);if(yt)return;
yt=new YT.Player(pl.querySelector('#plyt'),{width:'200',height:'200',playerVars:{playsinline:1,controls:0},events:{onReady:()=>{ready=true;ytq.splice(0).forEach(f=>f())},onStateChange:ev=>{if(mode!='y')return;const s=ev.data;if(s===1)ui(true);else if(s===2)ui(false);else if(s===0){ui(false);end()}},onError:()=>{ui(false);end(1)}}})});
const play=i=>{const it=its[i];if(!it)return;mark(i);const src=it.dataset.src,id=ytId(src);
if(id){au.pause();mode='y';ui(false);ensureYT(id,()=>{yt.loadVideoById(id);setTimeout(()=>{if(!dead&&mode=='y'&&!playing)pl.classList.add('blocked')},2200)})}
else{if(yt&&ready)try{yt.pauseVideo()}catch(e){}mode='a';au.src=src;const p=au.play();if(p&&p.catch)p.catch(()=>{ui(false);pl.classList.add('blocked')})}};
const end=err=>{let n=its.findIndex((x,k)=>k>cur&&x.dataset.auto=='1');if(n<0&&!err){n=its.findIndex(x=>x.dataset.auto=='1');if(n<0)n=cur}if(n>-1)play(n);else ui(false)};
const toggle=()=>{if(cur<0)return play(0);if(mode=='y'){if(!ready)return;playing?yt.pauseVideo():yt.playVideo()}else{playing?au.pause():au.play().catch(()=>{})}};
au.onplay=()=>ui(true);au.onpause=()=>ui(false);au.onended=()=>{ui(false);end()};au.onerror=()=>{ui(false)};au.onloadedmetadata=prog;
its.forEach((it,i)=>it.onclick=()=>{pl.classList.remove('blocked');i==cur?toggle():play(i)});
pp.onclick=()=>{pl.classList.remove('blocked');toggle()};
pl.querySelector('[data-pl-prev]').onclick=()=>play(Math.max(0,cur-1));
pl.querySelector('[data-pl-next]').onclick=()=>play((cur+1)%its.length);
seek.oninput=()=>{seeking=true};
seek.onchange=()=>{const r=seek.value/1000;if(mode=='y'&&ready)yt.seekTo(r*yt.getDuration(),true);else if(isFinite(au.duration))au.currentTime=r*au.duration;seeking=false};
const f=its.findIndex(x=>x.dataset.auto=='1');
const unlock=e=>{if(dead||playing||!pl.classList.contains('blocked'))return;if(e.target.closest&&e.target.closest('[data-pl]'))return;pl.classList.remove('blocked');play(f)};
if(f>-1){document.addEventListener('pointerdown',unlock,{once:true});play(f)}else{mark(0);const s=its[0].dataset.src;if(!ytId(s))au.src=s}
PLK=()=>{dead=true;clearInterval(timer);document.removeEventListener('pointerdown',unlock);au.pause();au.removeAttribute('src');try{yt&&yt.destroy&&yt.destroy()}catch(e){}}}
function shell(h){const p=location.hash;return`<div class="app"><aside><div class="logo">${E(D.s.name)}</div><a href="#/" class="nav-home ${p=='#/'||!p?'on':''}">⌂ <span>Trang chủ</span></a><a href="#/explore" class="${p=='#/explore'?'on':''}">✦ <span>Explore</span></a><a href="#/about" class="${p=='#/about'?'on':''}">♡ <span>About Me</span></a><a href="#/search" class="${p=='#/search'?'on':''}">⌕ <span>Tìm kiếm</span></a><div class="sp"></div>${admin?`<a href="#/admin/verses" class="${p.startsWith('#/admin')?'on':''}">⚙ <span>Quản trị</span></a><a href="#/logout">↪ <span>Đăng xuất</span></a>`:`<a href="#/login">♙ <span>Đăng nhập</span></a>`}</aside><main><div class="top"><div class="sb"><span class="search-icon">⌕</span><input id="q" placeholder="Search here..." autocomplete="off"><div class="dd" id="dd" hidden></div></div><div class="top-actions"><a href="#/about">♡</a><a href="#/explore">✦</a></div></div>${h}</main></div>`}
function ctrl(v){return V(v)?`style="--ac:${V(v).c}"`:''}
function render(){theme();const p=location.hash.slice(2).split('/'),[pg,a,b,c]=p;let h='';
if(pg=='admin'&&!admin||pg=='login'&&!admin)h=`<div class="panel auth"><div class="eyebrow">PRIVATE AREA</div><h2>Đăng nhập quản trị</h2><p>Chỉ quản trị viên mới được chỉnh sửa nội dung.</p><div class="row"><input class="f" id="em" type="email" placeholder="Email admin"><input class="f" id="pw" type="password" placeholder="Mật khẩu"><button class="btn" data-a="login">Đăng nhập</button></div><small id="err"></small></div>`;
else if(pg=='login')return location.hash='#/admin/verses';
else if(pg=='logout'){admin=false;if(sb)sb.auth.signOut();return location.hash='#/'}
else if(pg=='admin')h=adminView(a,b,c,p[4]);
else if(pg=='search')h=`<div class="eyebrow">SEARCH</div><h2>Tìm kiếm</h2><div class="row"><input class="f" id="q2" placeholder="Tìm verse, mục, nhân vật, nội dung..."></div><div class="row" id="fl">${['Tất cả','Verse','Mục','Bài viết'].map((x,i)=>`<button class="chip ${i?'':'selected'}" data-a="flt" data-k="${x}">${x}</button>`).join('')}</div><div id="res"></div>`;
else if(pg=='explore')h=exploreView();
else if(pg=='about')h=aboutView();
else if(pg=='v'&&V(a)){const v=V(a);h=`<div ${ctrl(a)}><div class="crumb"><a href="#/">Trang chủ</a> › Explore</div><div class="hero verse-hero" style="min-height:min(${FX(v,'img').h}px,75vh)">${fx(v,'img')}<div><span class="eyebrow">VERSE</span><h1>${E(v.n)}</h1><p>${E(v.d)}</p></div></div><div class="section-head"><div><span class="eyebrow">EXPLORE THIS WORLD</span><h2>Các mục</h2></div><span class="count">${v.s.length} mục</span></div><div class="grid">${v.s.map(s=>`<a class="card category-card" style="${dcs(s)}" href="#/s/${v.id}/${s.id}"><div class="tx"><span class="eyebrow">${v.s.indexOf(s)+1}</span><h3>${E(s.n)}</h3><p>${s.e.length} bài viết</p></div></a>`).join('')}</div>${admin?`<p><a class="btn g" href="#/admin/edit/${v.id}">Chỉnh sửa verse</a></p>`:''}</div>`}
else if(pg=='s'&&S(a,b)){const v=V(a),s=S(a,b);h=`<div ${ctrl(a)}><div class="crumb"><a href="#/explore">Explore</a> › <a href="#/v/${v.id}">${E(v.n)}</a></div><div class="section-head"><div><span class="eyebrow">${E(v.n)}</span><h1>${E(s.n)}</h1></div><span class="count">${s.e.length} bài</span></div><div class="grid">${s.e.map(e=>`<a class="card" style="${dcs(e)}" href="#/e/${a}/${b}/${e.id}"><div class="im" ${bg(e.img)}></div><div class="tx"><h3>${E(e.n)}</h3></div></a>`).join('')||'<div class="empty">Chưa có bài viết nào.</div>'}</div></div>`}
else if(pg=='e'&&T(a,b,c)){const v=V(a),s=S(a,b),e=T(a,b,c);h=`<div ${ctrl(a)}><div class="crumb"><a href="#/explore">Explore</a> › <a href="#/v/${v.id}">${E(v.n)}</a> › <a href="#/s/${a}/${b}">${E(s.n)}</a></div><article style="${dcs(e)}"><span class="eyebrow">${E(s.n)}</span><h1>${E(e.n)}</h1>${e.img?`<img ${imgStyle(e.imgSize,e.imgAr)} src="${e.img}" alt="" class="entry-cover">`:''}${e.b.map(b=>dcw(b,blockView(b))).join('')}${playlist(e)}${admin?`<p><a class="btn g" href="#/admin/entry/${a}/${b}/${c}">Sửa bài này</a></p>`:''}</article></div>`}
else h=homeView();
$('#root').innerHTML=shell(h);if($('#q2'))res();initPlaylist()}
function homeView(){return`<div class="dashboard-grid"><section class="home-main"><div class="hero home-hero" style="min-height:min(${FX(D.s,'cover').h}px,75vh)">${fx(D.s,'cover')}<div><span class="eyebrow">PRIVATE WIKI</span><h1>${E(D.s.name)}</h1><p>${E(D.s.note)}</p><div class="hero-actions"><a class="btn" href="#/explore">Explore Verse</a><a class="btn light" href="#/about">About Me</a></div></div></div><div class="section-head"><div><span class="eyebrow">YOUR WORLDS</span><h2>Verse của bạn</h2></div><a class="text-link" href="#/explore">Xem tất cả →</a></div><div class="grid">${D.v.map(v=>`<a class="card verse-card" href="#/v/${v.id}" style="border-top-color:${v.c}"><div class="im">${fx(v,'img')}</div><div class="tx"><h3>${E(v.n)}</h3><p>${E(v.d)}</p><small>${v.s.length} mục · ${v.s.reduce((n,s)=>n+s.e.length,0)} bài</small></div></a>`).join('')||'<div class="empty">Chưa có verse nào.</div>'}</div></section><aside class="home-side"><div class="mini-profile"><div class="avatar" ${bg(D.about.img)}></div><span class="eyebrow">ABOUT ME</span><h3>${E(D.about.title)}</h3><p>${E(D.about.subtitle)}</p><a class="text-link" href="#/about">Mở trang →</a></div><div class="mini-list"><span class="eyebrow">QUICK EXPLORE</span>${D.v.slice(0,4).map(v=>`<a href="#/v/${v.id}"><span class="dot" style="background:${v.c}"></span><span>${E(v.n)}</span><small>${v.s.length} mục</small></a>`).join('')}</div></aside></div>`}
function exploreView(){return`<div class="eyebrow">EXPLORE</div><div class="section-head"><div><h1>Khám phá các Verse</h1><p class="muted">Mỗi Verse đi kèm các mục nhỏ để bạn mở rộng thế giới theo cách riêng.</p></div><span class="count">${D.v.length} Verse</span></div><div class="explore-list">${D.v.map(v=>`<section class="explore-verse"><a class="explore-title" href="#/v/${v.id}"><div class="explore-avatar" style="border-color:${v.c}">${fx(v,'img')}</div><div><span class="eyebrow">VERSE</span><h2>${E(v.n)}</h2><p>${E(v.d)}</p></div><b>→</b></a><div class="sub-list">${v.s.map(s=>`<a href="#/s/${v.id}/${s.id}" style="${dcs(s)}"><span>${E(s.n)}</span><small>${s.e.length} bài</small><b>↗</b></a>`).join('')}</div></section>`).join('')||'<div class="empty">Chưa có Verse nào.</div>'}</div>`}
function aboutView(){const a=D.about;return`<div class="about-canvas" style="--about-bg:${a.bg};--about-ac:${a.ac};--about-ink:${a.ink};--radius:${a.radius}px"><div class="about-top ${a.img?'has-img':''}">${a.img?`<img ${AR(a.imgAr)?`style="aspect-ratio:${AR(a.imgAr)};object-fit:cover" `:''}src="${a.img}" alt="">`:''}<div><span class="eyebrow">ABOUT ME</span><h1>${E(a.title)}</h1><p>${E(a.subtitle)}</p></div></div><div class="about-intro"><p>${E(a.text)}</p></div><div class="about-blocks">${a.blocks.map(b=>dcw(b,aboutBlockView(b))).join('')}</div>${admin?`<a class="btn about-edit" href="#/admin/about">Chỉnh sửa About Me</a>`:''}</div>`}
function res(){const q=N($('#q2').value),f=window.flt||'Tất cả';$('#res').innerHTML='<div class="grid" style="grid-template-columns:1fr">'+items().filter(i=>(f=='Tất cả'||i.k==f)&&(!q||N(i.hay).includes(q))).slice(0,60).map(i=>`<a class="card" href="${i.h}" style="display:flex;gap:12px;align-items:center;padding:10px"><div class="th" ${bg(i.img)}></div><div><b>${E(i.n)}</b> <small>${i.k}</small><p>${E(i.sub)}</p></div></a>`).join('')+'</div>'}
const tabs=a=>`<div class="admin-title"><div><span class="eyebrow">CONTROL ROOM</span><h1>Quản trị</h1></div></div><div class="tabs">${[['verses','Verse'],['dash','Dashboard'],['about','About Me'],['edit','Chỉnh sửa chi tiết verse']].map(([k,l])=>`<a href="#/admin/${k}" class="${a==k||a=='entry'&&k=='edit'?'on':''}">${l}</a>`).join('')}</div>`;
const inp=(o,f,v,ph)=>`<input class="f" data-o="${o}" data-f="${f}" value="${E(v)}" placeholder="${ph||''}">`;
const up=(o,f,img,extra='')=>`<div class="upload-row"><div class="preview" ${bg(img)}></div><div><label class="btn g">${img?'Đổi ảnh':'Thêm ảnh'}<input type="file" accept="image/*" hidden data-up data-o="${o}" data-f="${f}"></label>${img?`<button class="btn d" data-a="delimg" data-o="${o}" data-f="${f}">Xóa ảnh</button>`:''}${extra}</div></div>`;
const sizeSelect=(o,f,v)=>`<label class="size-control">Kích thước <select class="f" data-o="${o}" data-f="${f}"><option value="25" ${+v===25?'selected':''}>25%</option><option value="40" ${+v===40?'selected':''}>40%</option><option value="60" ${+v===60?'selected':''}>60%</option><option value="75" ${+v===75?'selected':''}>75%</option><option value="100" ${+v===100?'selected':''}>100%</option></select></label>`;
const decoEd=(o,x)=>{const rg=(l,f,mn,mx,st,v)=>`<label class="size-control"><span>${l}</span><input type="range" min="${mn}" max="${mx}" step="${st}" value="${v}" data-o="${o}" data-f="${f}" data-deco><b>${v}%</b></label>`,br=x.br===undefined||x.br===''?18:+x.br,rd=`<label class="size-control"><span>Bo góc</span><input type="range" min="0" max="60" step="2" value="${br}" data-o="${o}" data-f="br" data-deco><b>${br}px</b></label>`;return`<div class="deco-ed"><b>🎨 Màu &amp; ảnh nền riêng</b><div class="row"><label>Màu nền <input type="color" data-o="${o}" data-f="bc" value="${x.bc||'#ffffff'}"></label><label>Màu chữ <input type="color" data-o="${o}" data-f="tc" value="${x.tc||D.s.ink}"></label><button class="btn g" data-a="resdeco" data-o="${o}">Bỏ màu &amp; ảnh</button></div><div class="deco-fr"><div class="deco-prevwrap"><div class="deco-prev" style="${dcs(x,1)}"><span>Khung nền · Xem trước</span></div></div><div class="deco-sl">${rd}${rg('Trong suốt','bt',0,100,5,x.bt??0)}${x.bi?rg('Độ phủ sáng','bo',0,90,5,x.bo??55):''}${/^(b|ab):/.test(o)?arSelect(o,'far',x.far,'Tỉ lệ khung')+`<label class="size-control">Rộng khung <select class="f" data-o="${o}" data-f="fw">${[25,40,60,75,100].map(k=>`<option value="${k}" ${+(x.fw||100)===k?'selected':''}>${k}%</option>`).join('')}</select></label>`:''}</div></div>${x.bi?'<p class="muted" style="margin:4px 0">Đang dùng ảnh thay cho màu nền. Bấm <b>Xóa ảnh</b> để quay lại màu.</p>':''}${up(o,'bi',x.bi)}<div class="row">${inp(o,'bi',x.bi&&x.bi.startsWith('data:')?'':x.bi,'Hoặc dán link ảnh / GIF nền')}</div></div>`};
function adminView(a,b,c,d){let h=tabs(a);
if(a=='verses'||!a)h+=`<button class="btn" data-a="addv">+ Thêm verse</button>`+`<div data-drag-list="verses">`+D.v.map((v,vi)=>`<div class="panel admin-verse" data-drag-item="${vi}"><div class="row">${GRIP}${inp('v:'+v.id,'n',v.n,'Tên verse')}<input type="color" data-o="v:${v.id}" data-f="c" value="${v.c}" title="Màu verse">${del('delv','data-id="'+v.id+'"')}<a class="btn g" href="#/v/${v.id}">Xem</a></div>${inp('v:'+v.id,'d',v.d,'Mô tả ngắn')}${up('v:'+v.id,'img',v.img)}${fxEditor('v:'+v.id,'img',v)}</div>`).join('')+'</div>';
else if(a=='dash'){const s=D.s;h+=`<div class="panel"><span class="eyebrow">HOME DASHBOARD</span><h3>Giao diện chính</h3><div class="row">${inp('st','name',s.name,'Tên wiki')}</div><div class="row">${inp('st','note',s.note,'Ghi chú / mô tả')}</div><div class="row"><label>Màu chủ đạo <input type="color" data-o="st" data-f="ac" value="${s.ac}"></label><label>Màu nền <input type="color" data-o="st" data-f="bg" value="${s.bg}"></label><label>Màu chữ <input type="color" data-o="st" data-f="ink" value="${s.ink}"></label><button class="btn g" data-a="rescol">Về màu mặc định</button></div></div><div class="panel"><h3>Ảnh dashboard</h3><p class="muted">Thêm, thay hoặc gỡ ảnh, rồi chỉnh chiều cao, độ phóng to và vị trí.</p>${up('st','cover',s.cover)}${fxEditor('st','cover',s)}</div><div class="panel"><span class="eyebrow">ĐĂNG WEB</span><h3>Sao lưu &amp; đăng lên GitHub</h3><p class="muted">Dữ liệu tự lưu lên Supabase mỗi khi bạn chỉnh sửa nên mọi người đều xem được. Xuất/Nhập chỉ để sao lưu. Dung lượng dữ liệu ~${memUse().toFixed(1)} MB — nếu lớn, bấm <b>Chuyển ảnh/nhạc cũ lên Storage</b>.</p><div class="row"><button class="btn" id="expbtn">⬇ Xuất dữ liệu (data.json)</button><label class="btn g">⬆ Nhập dữ liệu<input type="file" accept=".json,application/json" hidden id="impf"></label><button class="btn g" id="migbtn">☁ Chuyển ảnh/nhạc cũ lên Storage</button><button class="btn d" id="pubbtn">Xóa cache máy này và tải lại từ Supabase</button></div></div>`}
else if(a=='about')h+=aboutAdmin();
else if(a=='edit'&&!b)h+=`<div class="grid">${D.v.map(v=>`<a class="card" href="#/admin/edit/${v.id}" style="border-top-color:${v.c}"><div class="tx"><h3>${E(v.n)}</h3><p>Chọn để chỉnh chi tiết</p></div></a>`).join('')}</div>`;
else if(a=='edit'&&V(b)){const v=V(b);h+=`<h3>${E(v.n)}</h3><div class="panel"><div class="row"><input class="f" id="ns" placeholder="Tên mục mới (vd: Nhân vật)"><button class="btn" data-a="adds" data-id="${b}">+ Thêm mục</button></div>${['Nhân vật','Địa điểm','Cốt truyện','Timeline','Thế lực','Vật phẩm'].map(x=>`<button class="chip" data-a="adds" data-id="${b}" data-n="${x}">${x}</button>`).join('')}</div>`+`<div data-drag-list="sections:${b}">`+v.s.map((s,si)=>`<div class="panel" data-drag-item="${si}"><div class="row">${GRIP}${inp(`s:${b}:${s.id}`,'n',s.n)}${del('dels',`data-v="${b}" data-id="${s.id}"`,'Xóa mục')}</div>${decoEd(`s:${b}:${s.id}`,s)}<div data-drag-list="entries:${b}:${s.id}">${s.e.map((e,ei)=>`<div class="row" data-drag-item="${ei}">${GRIP}<div class="th" ${bg(e.img)}></div><a class="btn g" href="#/admin/entry/${b}/${s.id}/${e.id}" style="flex:1">${E(e.n)}</a>${del('dele',`data-v="${b}" data-s="${s.id}" data-id="${e.id}"`)}</div>`).join('')}</div><div class="row"><input class="f" id="ne${s.id}" placeholder="Tên bài viết mới"><button class="btn" data-a="adde" data-v="${b}" data-id="${s.id}">+ Thêm bài</button></div></div>`).join('')+'</div>'}
else if(a=='entry'&&T(b,c,d)){const e=T(b,c,d),P=`${b}:${c}:${d}`;h+=`<div class="crumb"><a href="#/admin/edit/${b}">← Quay lại verse</a> · <a href="#/e/${b}/${c}/${d}">Xem trang</a></div><div class="panel">${inp('e:'+P,'n',e.n,'Tên bài')}${e.img?up('e:'+P,'img',e.img,sizeSelect('e:'+P,'imgSize',e.imgSize)+arSelect('e:'+P,'imgAr',e.imgAr)):up('e:'+P,'img','',sizeSelect('e:'+P,'imgSize',e.imgSize)+arSelect('e:'+P,'imgAr',e.imgAr))}${decoEd('e:'+P,e)}</div>`+`<div data-drag-list="blocks:${P}">`+e.b.map((x,i)=>{const o=`b:${P}:${i}`,L={heading:'Tiêu đề mục',text:'Đoạn chữ',img:'Ảnh',imgtext:'Ảnh + chữ',video:'Video',audio:'Nhạc',info:'Bảng thông tin'}[x.t];let f='';
if(x.t=='heading')f=inp(o,'v',x.v,'Tự đặt tiêu đề');if(x.t=='text')f=`<textarea class="f" data-o="${o}" data-f="v">${E(x.v)}</textarea>`;if(x.t=='info')f=`<textarea class="f" data-o="${o}" data-f="v" placeholder="Mỗi dòng: Tên: giá trị">${E(x.v)}</textarea>`;
if(x.t=='img'||x.t=='imgtext')f=`${x.img?`<img ${imgStyle(x.size,x.ar)} src="${x.img}" alt="">`:''}<div class="row"><label class="btn g">${x.img?'Đổi ảnh':'Chọn ảnh'}<input type="file" accept="image/*" hidden data-up data-o="${o}" data-f="img"></label>${x.img?`<button class="btn d" data-a="delimg" data-o="${o}" data-f="img">Xóa ảnh</button>`:''}${sizeSelect(o,'size',x.size||100)}${arSelect(o,'ar',x.ar)}${x.t=='img'?inp(o,'cap',x.cap,'Chú thích'):`<select class="f" data-o="${o}" data-f="side"><option value="L">Ảnh bên trái</option><option value="R" ${x.side=='R'?'selected':''}>Ảnh bên phải</option></select>`}</div><div class="row">${inp(o,'img',x.img&&x.img.startsWith('data:')?'':x.img,'Hoặc dán link ảnh / GIF')}</div>${x.t=='imgtext'?`<textarea class="f" data-o="${o}" data-f="v">${E(x.v)}</textarea>`:''}`;
if(x.t=='video'||x.t=='audio')f=`<div class="row">${inp(o,'v',x.v&&x.v.startsWith('data:')?'':x.v,x.t=='audio'?'Dán link nhạc (.mp3, .ogg... hoặc YouTube)':'Dán link (YouTube hoặc file .mp4)')}<label class="btn g">Tải file<input type="file" accept="${x.t}/*" hidden data-up data-o="${o}" data-f="v"></label></div>${x.v?.startsWith('data:')?'<small>Đã tải file lên.</small>':''}`;
if(x.t=='audio')f+=`<div class="row">${inp(o,'title',x.title,'Tên bài hát (hiện trong playlist)')}<label class="chk"><input type="checkbox" data-o="${o}" data-f="auto" ${x.auto?'checked':''}> ▶ Tự động phát</label></div><small class="muted">Nhạc gom thành playlist nhỏ ở cuối bài (không hiện video). Bài đứng trên phát trước, bài dưới phát sau — kéo ⋮⋮ để đổi thứ tự. Bật “Tự động phát” để người xem vào bài là nghe luôn.</small>`;
return`<div class="blk" data-drag-item="${i}"><div class="bh">${GRIP}<b>${L}</b><button class="btn g" data-a="mv" data-p="${P}" data-i="${i}" data-d="-1">↑</button><button class="btn g" data-a="mv" data-p="${P}" data-i="${i}" data-d="1">↓</button>${del('delb',`data-p="${P}" data-i="${i}"`)}</div>${f}${x.t=='audio'?'':decoEd(o,x)}</div>`}).join('')+'</div>'+`<div class="panel"><b>Thêm khối:</b> ${[['heading','Tiêu đề'],['text','Chữ'],['img','Ảnh'],['imgtext','Ảnh + chữ'],['video','Video'],['audio','Nhạc'],['info','Bảng thông tin']].map(([k,l])=>`<button class="chip" data-a="addb" data-p="${P}" data-t="${k}">+ ${l}</button>`).join('')}</div>`}
return h}
function aboutAdmin(){const a=D.about;return`<div class="panel about-editor"><div class="editor-heading"><div><span class="eyebrow">CANVA-STYLE EDITOR</span><h2>About Me</h2><p class="muted">Chỉnh bố cục, màu sắc, ảnh và từng khối nội dung.</p></div><a class="btn g" href="#/about">Xem trang</a></div><div class="about-settings"><div>${inp('about','title',a.title,'Tiêu đề')}${inp('about','subtitle',a.subtitle,'Dòng giới thiệu')}<textarea class="f" data-o="about" data-f="text" placeholder="Nội dung giới thiệu">${E(a.text)}</textarea></div><div class="style-box"><b>Phong cách</b><div class="row"><label>Nền <input type="color" data-o="about" data-f="bg" value="${a.bg}"></label><label>Màu nhấn <input type="color" data-o="about" data-f="ac" value="${a.ac}"></label><label>Chữ <input type="color" data-o="about" data-f="ink" value="${a.ink}"></label></div><div class="row"><label>Bo góc <input class="f" type="number" min="0" max="60" data-o="about" data-f="radius" value="${a.radius}"></label></div></div></div>${up('about','img',a.img,a.img?arSelect('about','imgAr',a.imgAr,'Tỉ lệ ảnh'):'')}<small class="muted">Dữ liệu đang dùng ~${memUse().toFixed(1)} MB</small><div class="panel inner-panel"><b>Khối nội dung</b><div class="row"><button class="chip" data-a="aboutadd" data-t="heading">+ Tiêu đề</button><button class="chip" data-a="aboutadd" data-t="text">+ Văn bản</button><button class="chip" data-a="aboutadd" data-t="img">+ Ảnh</button><button class="chip" data-a="aboutadd" data-t="imgtext">+ Ảnh + chữ</button></div><div data-drag-list="about">${a.blocks.map((x,i)=>{const o=`ab:${i}`;return`<div class="blk" data-drag-item="${i}"><div class="bh">${GRIP}<b>${x.t==='heading'?'Tiêu đề':x.t==='text'?'Văn bản':x.t==='img'?'Ảnh':'Ảnh + chữ'}</b><button class="btn g" data-a="aboutmv" data-i="${i}" data-d="-1">↑</button><button class="btn g" data-a="aboutmv" data-i="${i}" data-d="1">↓</button>${del('aboutdel',`data-i="${i}"`)}</div>${x.t==='heading'?inp(o,'v',x.v,'Tiêu đề'):x.t==='text'?`<textarea class="f" data-o="${o}" data-f="v">${E(x.v)}</textarea>`:`${x.img?`<img ${imgStyle(x.size,x.ar)} src="${x.img}" alt="">`:''}<div class="row"><label class="btn g">${x.img?'Đổi ảnh':'Chọn ảnh'}<input type="file" accept="image/*" hidden data-up data-o="${o}" data-f="img"></label>${x.img?`<button class="btn d" data-a="delimg" data-o="${o}" data-f="img">Xóa ảnh</button>`:''}${sizeSelect(o,'size',x.size||100)}${arSelect(o,'ar',x.ar)}${x.t==='imgtext'?`<select class="f" data-o="${o}" data-f="side"><option value="L">Ảnh trái</option><option value="R" ${x.side==='R'?'selected':''}>Ảnh phải</option></select>`:''}</div><div class="row">${inp(o,'img',x.img&&x.img.startsWith('data:')?'':x.img,'Hoặc dán link ảnh / GIF')}</div>${x.t==='imgtext'?`<textarea class="f" data-o="${o}" data-f="v" placeholder="Văn bản">${E(x.v)}</textarea>`:''}`}${decoEd(o,x)}</div>`}).join('')}</div></div></div>`}
function obj(o){const p=o.split(':');if(p[0]=='st')return D.s;if(p[0]=='about')return D.about;if(p[0]=='v')return V(p[1]);if(p[0]=='s')return S(p[1],p[2]);if(p[0]=='e')return T(p[1],p[2],p[3]);if(p[0]=='b')return T(p[1],p[2],p[3]).b[p[4]];if(p[0]=='ab')return D.about.blocks[p[1]]}
document.addEventListener('input',e=>{const t=e.target;if(t.id=='q'){const q=N(t.value),dd=$('#dd'),r=D.v.filter(v=>q&&N(v.n+' '+v.d).includes(q)).slice(0,6);dd.hidden=!r.length;dd.innerHTML=r.map(v=>`<a href="#/v/${v.id}"><div class="th" style="width:34px;height:34px;${v.img?`background-image:url('${v.img}')`:''}"></div><div>${E(v.n)}<br><small>Verse</small></div></a>`).join('');return}if(t.id=='q2')return res();if(t.dataset.o&&t.type!='file'){const o=obj(t.dataset.o);if(o){o[t.dataset.f]=t.type=='checkbox'?t.checked:/^(img|bi)$/.test(t.dataset.f)?linkFix(t.value):t.value;save();if(t.dataset.o=='st')theme();if(t.dataset.pv)fxLive(t,o);if(t.dataset.deco!==undefined){const b=t.parentElement.querySelector('b');if(b)b.textContent=t.value+(t.dataset.f=='br'?'px':'%');const pv=t.closest('.deco-ed')?.querySelector('.deco-prev');if(pv)pv.style.cssText=dcs(o,1)}}}});
document.addEventListener('keydown',e=>{if(e.key=='Enter'&&e.target.id=='q'){const a=$('#dd a');if(a)location.hash=a.getAttribute('href');e.target.blur();$('#dd').hidden=true}if(e.key=='Enter'&&e.target.id=='pw')$('[data-a=login]').click()});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.up!==undefined&&t.files[0]){const f=t.files[0],o=obj(t.dataset.o);readImg(f,async u=>{if(!u)return;const old=o[t.dataset.f];o[t.dataset.f]=u;if(!await save())o[t.dataset.f]=old;render()},/^image/.test(t.accept||''));t.value='';return}if(t.dataset.pv)return;if(t.dataset.o&&t.type!=='file'){const o=obj(t.dataset.o);if(o){o[t.dataset.f]=t.type=='checkbox'?t.checked:/^(img|bi)$/.test(t.dataset.f)?linkFix(t.value):t.value;save();render()}}});
let armed;
document.addEventListener('click',e=>{if(!e.target.closest('.sb')&&$('#dd'))$('#dd').hidden=true;const t=e.target.closest('[data-a]');if(!t)return;const a=t.dataset.a,d=t.dataset;if(d.danger!==undefined&&armed!==t){if(armed){armed.classList.remove('armed');armed.textContent=armed.dataset.tx}armed=t;d.tx=t.textContent;t.classList.add('armed');t.textContent='Bấm lại để xóa';return}armed=null;const nm=id=>{const el=$('#'+id);return el?el.value.trim():''};
if(a=='login'){if(!sb){$('#err').textContent='Chưa cấu hình Supabase (SB_URL / SB_KEY ở đầu app.js).';return}sb.auth.signInWithPassword({email:$('#em').value.trim(),password:$('#pw').value}).then(({error})=>{if(error){$('#err').textContent='Sai email hoặc mật khẩu.';return}admin=true;location.hash='#/admin/verses';render()});return}
if(a=='flt'){window.flt=d.k;document.querySelectorAll('#fl .chip').forEach(c=>c.classList.toggle('selected',c==t));return res()}
if(a=='addv')D.v.push({id:uid(),n:'Verse mới',d:'',c:D.s.ac,img:'',s:[{id:uid(),n:'Nhân vật',e:[]},{id:uid(),n:'Địa điểm',e:[]},{id:uid(),n:'Cốt truyện',e:[]},{id:uid(),n:'Timeline',e:[]}]});
if(a=='delv')D.v=D.v.filter(v=>v.id!=d.id);
if(a=='rescol')Object.assign(D.s,DEF);
if(a=='adds'){const n=d.n||nm('ns');if(!n)return;V(d.id).s.push({id:uid(),n,e:[]})}
if(a=='dels')V(d.v).s=V(d.v).s.filter(s=>s.id!=d.id);
if(a=='adde'){const n=nm('ne'+d.id);if(!n)return;S(d.v,d.id).e.push({id:uid(),n,img:'',imgSize:100,b:[]})}
if(a=='dele')S(d.v,d.s).e=S(d.v,d.s).e.filter(x=>x.id!=d.id);
if(a=='addb'){const e=T(...d.p.split(':'));e.b.push({t:d.t,v:'',img:'',cap:'',side:'L',size:100})}
if(a=='delb')T(...d.p.split(':')).b.splice(+d.i,1);
if(a=='mv'){const b=T(...d.p.split(':')).b,i=+d.i,j=i+ +d.d;if(j<0||j>=b.length)return;[b[i],b[j]]=[b[j],b[i]]}
if(a=='resdeco'){const o=obj(d.o);if(o)['bc','tc','bi','bo','br','bt','far','fw'].forEach(k=>delete o[k])}
if(a=='delimg'){const o=obj(d.o);if(o)o[d.f]=''}
if(a=='resfx'){const o=obj(d.o);if(o)['H','Z','X','Y'].forEach(p=>delete o[d.k+p])}
if(a=='aboutadd')D.about.blocks.push({t:d.t,v:d.t==='heading'?'Tiêu đề mới':'',img:'',side:'L',size:100});
if(a=='aboutdel')D.about.blocks.splice(+d.i,1);
if(a=='aboutmv'){const i=+d.i,j=i+ +d.d,b=D.about.blocks;if(j<0||j>=b.length)return;[b[i],b[j]]=[b[j],b[i]]}
save();render()});
let dg;
const dragArr=k=>{const p=k.split(':');if(p[0]=='verses')return D.v;if(p[0]=='sections')return V(p[1])?.s;if(p[0]=='entries')return S(p[1],p[2])?.e;if(p[0]=='blocks')return T(p[1],p[2],p[3])?.b;if(p[0]=='about')return D.about.blocks};
document.addEventListener('pointerdown',e=>{const g=e.target.closest('[data-grip]');if(!g||e.button)return;const it=g.closest('[data-drag-item]'),ls=it&&it.parentElement;if(!ls||ls.dataset.dragList===undefined)return;e.preventDefault();dg={it,ls,y:e.pageY,top:it.getBoundingClientRect().top+scrollY};it.classList.add('dragging');document.body.classList.add('drag-on');try{g.setPointerCapture(e.pointerId)}catch(_){}});
document.addEventListener('pointermove',e=>{if(!dg)return;const{it,ls}=dg;if(e.clientY<70)scrollBy(0,-16);else if(e.clientY>innerHeight-70)scrollBy(0,16);const py=e.clientY+scrollY,mid=x=>{const r=x.getBoundingClientRect();return r.top+r.height/2},place=()=>{it.style.transform='';const n=it.getBoundingClientRect().top+scrollY;it.style.transform=`translateY(${dg.top+(py-dg.y)-n}px)`};place();let s;while((s=it.previousElementSibling)&&s.dataset.dragItem!==undefined&&mid(it)<mid(s)){ls.insertBefore(it,s);place()}while((s=it.nextElementSibling)&&s.dataset.dragItem!==undefined&&mid(it)>mid(s)){ls.insertBefore(s,it);place()}});
function endDrag(){if(!dg)return;const{it,ls}=dg;dg=null;it.classList.remove('dragging');it.style.transform='';document.body.classList.remove('drag-on');const order=[...ls.children].filter(x=>x.dataset.dragItem!==undefined).map(x=>+x.dataset.dragItem),arr=dragArr(ls.dataset.dragList);if(arr&&order.length==arr.length&&order.some((v,i)=>v!==i)){const n=order.map(i=>arr[i]);arr.splice(0,arr.length,...n);save()}render()}
document.addEventListener('pointerup',endDrag);document.addEventListener('pointercancel',endDrag);
document.addEventListener('error',e=>{const im=e.target;if(!im||im.tagName!=='IMG'||im.dataset.werr||!im.closest('#root'))return;im.dataset.werr=1;const w=document.createElement('div');w.className='img-warn';w.textContent='Ảnh không tải được (link hỏng, hết hạn hoặc file lỗi). Vào Quản trị để thêm lại ảnh — nên bấm “Tải ảnh lên” thay vì dán link.';im.replaceWith(w)},true);
addEventListener('hashchange',render);
(async()=>{let raw,remoteEmpty=false,remoteError=null,remoteLoaded=false;
if(sb){try{const{data:ss,error:se}=await sb.auth.getSession();if(se)throw se;admin=!!ss.session}catch(e){remoteError=e}
try{const{data:row,error}=await sb.from('wiki').select('data').eq('id','main').maybeSingle();if(error)throw error;remoteLoaded=true;if(row&&row.data)raw=JSON.stringify(row.data);else remoteEmpty=true}catch(e){remoteError=e}}
if(raw==null){try{raw=await idbGet()}catch(e){}}
if(raw==null){try{raw=localStorage.getItem(KEY)}catch(e){}}
if(raw==null){try{const r=await fetch('data.json?v='+Date.now(),{cache:'no-store'});if(r.ok){const t=await r.text();JSON.parse(t);raw=t}}catch(e){}}
boot(raw);render();
if(remoteLoaded&&raw!=null)await cacheLocal(JSON.stringify(D));
if(sb&&remoteError)toast('⚠ Không tải được dữ liệu Supabase — đang dùng bản cache');
if(sb&&admin&&remoteEmpty&&raw!=null){try{await pushRemote(JSON.stringify(D));await cacheLocal(JSON.stringify(D));toast('✓ Đã tạo dữ liệu chung trên Supabase')}catch(e){alert('Không thể tạo dữ liệu chung trên Supabase: '+(e?.message||e))}}
})();
document.addEventListener('click',async e=>{const b=e.target.closest('#expbtn,#pubbtn');if(!b)return;if(b.id==='expbtn'){const u=URL.createObjectURL(new Blob([JSON.stringify(D)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='data.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2e3);return}
if(!confirm('Xóa cache trên máy này và tải lại dữ liệu chung từ Supabase?'))return;try{const db=await idb();await new Promise((ok,no)=>{const tx=db.transaction('kv','readwrite');tx.objectStore('kv').delete(KEY);tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}catch(_){}try{localStorage.removeItem(KEY)}catch(_){}location.reload()});
document.addEventListener('change',e=>{const t=e.target;if(t.id!=='impf'||!t.files[0])return;const f=t.files[0];t.value='';const r=new FileReader();r.onerror=()=>alert('Không đọc được file này.');r.onload=async()=>{try{const j=JSON.parse(r.result);if(!j||!Array.isArray(j.v)||!j.s)throw 0;if(!confirm('Thay toàn bộ dữ liệu hiện tại bằng nội dung file này?'))return;D=null;boot(r.result);if(await save())alert('Đã nhập dữ liệu.');render()}catch(_){alert('File này không phải data.json của web này.')}};r.readAsText(f)});

document.addEventListener('click',async e=>{const b=e.target.closest('#migbtn');if(!b)return;if(!sb||!admin)return alert('Cần đăng nhập admin bằng Supabase trước.');if(!confirm('Tải toàn bộ ảnh/nhạc đang nhúng trong dữ liệu lên Supabase Storage và thay bằng link?'))return;b.disabled=true;const seen=new Map();let n=0,bad=0;const walk=async o=>{for(const k of Object.keys(o)){const v=o[k];if(typeof v==='string'&&/^data:(image|audio|video)\//.test(v)){if(!seen.has(v)){try{seen.set(v,await upMedia(v));n++;b.textContent='Đã chuyển '+n+'…'}catch(_){seen.set(v,null);bad++}}if(seen.get(v))o[k]=seen.get(v)}else if(v&&typeof v==='object')await walk(v)}};await walk(D);await save();alert('Xong: chuyển '+n+' file'+(bad?', lỗi '+bad+' file (giữ nguyên)':'')+'.');render()});
